name: Build Wubi

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  Build-Wubi:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y git make gettext unzip wget wine32:i386
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Build
        run: |
          cd ${{ github.workspace }}
          make
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: wubi.exe
          path: ${{ github.workspace }}/build/wubi.exe
